#!/bin/bash
# WF 2024-05-05
# restore the snapquery database
db=$HOME/.solutions/snapquery/storage/named_queries.db
rm $db
for f in $(find snapquery/samples -name '*.json')
do
  snapquery --import  $f | grep -iv warning
done
#sqlite_web $db
